### ISSUE TITLE
Problem z wyjściem z zakładki "O projekcie" i "O programie"

### ISSUE THREAD

**Issue by ghost** [by-speece/python-c-MiU#1]
Naciśnij Enter by wrócić do Menu....

Po wciśnięciu Enter pojawia się poniższa wiadomość:

Traceback (most recent call last):
  File "start.py", line 165, in <module>
  File "start.py", line 40, in startx
  File "start.py", line 156, in menu
  File "start.py", line 29, in powrot_menu
NameError: name 'enter' is not defined
[15390] Failed to execute script start

**Comment by szymongalka** [comment]
Naprawione w najnowszej wersji
